ema:
  full_name: 樱羽艾玛
  emotion_count: 11
  offset: [-180,1700]
  scale: 0.4
  font: font3
  text:  
    - text: 樱
      font_color: [253, 145, 175]
      font_size: 136
    - text: 羽
      font_size: 76
    - text: 艾
      font_size: 116
    - text: 玛
      font_size: 76
  "平静": [3]
  "喜悦": [3,8]
  "喜爱": [6,11,10]
  "惊讶": [9]
  "困惑": [7]
  "无语": [4,7]
  "悲伤": [2,6,10,11]
  "愤怒": [1,4]
  "恐惧": [2,5]
hiro:
  full_name: 二阶堂希罗
  emotion_count: 16
  offset: [-350,1750]
  scale: 0.5
  font: font3
  text:
    - text: 二
      font_color: [239, 79, 84]
      font_size: 136
    - text: 阶堂
      font_size: 76
    - text: 希
      font_size: 116
    - text: 罗
      font_size: 76
  "平静": [5,6]
  "喜悦": [5,6,13,14]
  "喜爱": [9,10]
  "惊讶": [15,16]
  "困惑": [11,12,15,16]
  "无语": [7,13,14]
  "悲伤": [3,4,11,12]
  "愤怒": [1,2]
  "恐惧": [7,8]
CreatureHiro:
  full_name: 二阶堂希罗（魔女化）
  emotion_count: 25
  font: font3
  text:
    - text: 二
      font_color: [239, 79, 84]
      font_size: 136
    - text: 阶堂
      font_size: 76
    - text: 希
      font_size: 116
    - text: 罗
      font_size: 76
  offset: [-160,1790]
  offsetX:
    "2": -40
    "3": -40
    "5": -40
    "6": -330
    "7": -330
    "8": -330
    "9": -330
    "12": -40
    "15": -40
  scale: 0.41
  "平静": [1,2,3,5,8,9,10,11]
  "喜悦": [3,5,8,10,11,25]
  "喜爱": [25]
  "惊讶": [1,15,23,24]
  "困惑": [1,15,17,23]
  "无语": [1,2,4,15,16,23,24,25]
  "悲伤": [9]
  "愤怒": [4,7,14,17,20,22,23,24]
  "恐惧": [12,13,15]
sherry:
  full_name: 橘雪莉
  emotion_count: 8
  offset: [-350,2100]
  scale: 0.47
  font: font3
  text:
    - text: 橘
      font_color: [137, 177, 251]
      font_size: 136
    - text: 雪
      font_size: 116
    - text: 莉
      font_size: 76
  "平静": [3,6]
  "喜悦": [3,7]
  "喜爱": [5,7]
  "惊讶": [8]
  "困惑": [6]
  "无语": [1,6]
  "悲伤": [2,6]
  "愤怒": [1]
  "恐惧": [4]
hanna:
  full_name: 远野汉娜
  emotion_count: 8
  offset: [-480,1750]
  scale: 0.45
  font: font3
  text:
    - text: 远
      font_color: [169, 199, 30]
      font_size: 136
    - text: 野
      font_size: 76
    - text: 汉
      font_size: 116
    - text: 娜
      font_size: 76
  "平静": [3,7]
  "喜悦": [3,7]
  "喜爱": [3,5,6]
  "惊讶": [8]
  "困惑": [3]
  "无语": [3,6]
  "悲伤": [2,5]
  "愤怒": [1,3]
  "恐惧": [4,6]
anan:
  full_name: 夏目安安
  emotion_count: 12
  offset: [-550,1850]
  scale: 0.48
  font: font3
  text:
    - text: 夏
      font_color: [159, 145, 251]
      font_size: 136
    - text: 目
      font_size: 76
    - text: 安
      font_size: 116
    - text: 安
      font_size: 76
  "平静": [7]
  "喜悦": [5,7,9,11]
  "喜爱": [5,9,11]
  "惊讶": [3,8]
  "困惑": [3,6,10]
  "无语": [1,3,7,10,12]
  "悲伤": [2,3,6]
  "愤怒": [1,4]
  "恐惧": [1,6,10,12]
yuki:
  full_name: 月代雪
  emotion_count: 20
  offset: [-550,1850]
  scale: 0.47
  font: font3
  text:
    - text: 月
      font_color: [195, 209, 231]
      font_size: 136
    - text: 代
      font_size: 76
    - text: 雪
      font_size: 116
  offsetY:
    "12": 50
  "平静": [2,3,4,5]
  "喜悦": [2,3,4,5,6,7,8,18,19]
  "喜爱": [8,18,19]
  "惊讶": [9,13,15,16,17]
  "困惑": [9,13,15,20]
  "无语": [1,4,5,10,11,14,16,17,19,20]
  "悲伤": [17]
  "愤怒": [1,7,13,16,17]
  "恐惧": [16,17]
meruru:
  full_name: 冰上梅露露
  emotion_count: 16
  offset: [-200,1900]
  scale: 0.55
  font: font3
  text:
    - text: 冰
      font_color: [227, 185, 175]
      font_size: 136
    - text: 上
      font_size: 76
    - text: 梅
      font_size: 116
    - text: 露露
      font_size: 76
  "平静": [13,14]
  "喜悦": [13,14]
  "喜爱": [8,9,13,14]
  "惊讶": [15,16]
  "困惑": [15,16]
  "无语": [1,9,10,13]
  "悲伤": [3,4,6,5,11,12]
  "愤怒": [1,2]
  "恐惧": [7,8]
noa:
  full_name: 城崎诺亚
  emotion_count: 8
  offset: [-500,1950]
  scale: 0.47
  font: font3
  text:
    - text: 城
      font_color: [104, 223, 231]
      font_size: 136
    - text: 崎
      font_size: 76
    - text: 诺
      font_size: 116
    - text: 亚
      font_size: 76
  "平静": [3]
  "喜悦": [3,7]
  "喜爱": [1,5,7]
  "惊讶": [8]
  "困惑": [3,6]
  "无语": [1,3,6,7]
  "悲伤": [2,6]
  "愤怒": [1]
  "恐惧": [4,6]
reia:
  full_name: 莲见蕾雅
  emotion_count: 8
  offset: [-420,2600]
  scale: 0.54
  font: font3
  text:
    - text: 莲
      font_color: [253, 177, 88]
      font_size: 136
    - text: 见
      font_size: 76
    - text: 蕾
      font_size: 116
    - text: 雅
      font_size: 76
  "平静": [3,7]
  "喜悦": [7]
  "喜爱": [5,7]
  "惊讶": [8]
  "困惑": [3,6,8]
  "无语": [1,3]
  "悲伤": [2,6]
  "愤怒": [1]
  "恐惧": [4]
miria:
  full_name: 佐伯米莉亚
  emotion_count: 8
  offset: [-300,2200]
  scale: 0.49
  font: font3
  text:
    - text: 佐
      font_color: [235, 207, 139]
      font_size: 136
    - text: 伯
      font_size: 76
    - text: 米
      font_size: 116
    - text: 莉亚
      font_size: 76
  "平静": [7]
  "喜悦": [7]
  "喜爱": [5,7]
  "惊讶": [3,8]
  "困惑": [6]
  "无语": [1,6,7]
  "悲伤": [2,6]
  "愤怒": [1,]
  "恐惧": [4,8]
nanoka:
  full_name: 黑部奈叶香
  emotion_count: 8
  offset: [-450,1975]
  scale: 0.56
  font: font3
  text:
    - text: 黑
      font_color: [131, 143, 147]
      font_size: 136
    - text: 部
      font_size: 76
    - text: 奈
      font_size: 116
    - text: 叶香
      font_size: 76
  "平静": [3,7]
  "喜悦": [3,7]
  "喜爱": [5,7]
  "惊讶": [3,8]
  "困惑": [3,6]
  "无语": [1]
  "悲伤": [2,6]
  "愤怒": [1]
  "恐惧": [4]
mago:
  full_name: 宝生玛格
  emotion_count: 8
  offset: [-300,2140]
  scale: 0.47
  font: font3
  text:
    - text: 宝
      font_color: [185, 124, 235]
      font_size: 136
    - text: 生
      font_size: 76
    - text: 玛
      font_size: 116
    - text: 格
      font_size: 76
  "平静": [3]
  "喜悦": [3,5,7]
  "喜爱": [5,7]
  "惊讶": [8]
  "困惑": [6]
  "无语": [1,3,6]
  "悲伤": [2]
  "愤怒": [1]
  "恐惧": [4]
alisa:
  full_name: 紫藤亚里沙
  emotion_count: 8
  offset: [-180,2000]
  scale: 0.46
  font: font3
  text:
    - text: 紫
      font_color: [235, 75, 60]
      font_size: 136
    - text: 藤
      font_size: 76
    - text: 亚
      font_size: 116
    - text: 里沙
      font_size: 76
  "平静": [3,6,7]
  "喜悦": [7]
  "喜爱": [7]
  "惊讶": [5,8]
  "困惑": [3]
  "无语": [1,5,6,7]
  "悲伤": [2]
  "愤怒": [1]
  "恐惧": [2,4]
coco:
  full_name: 泽渡可可    
  emotion_count: 8
  offset: [-200,1920]
  scale: 0.45
  font: font3
  text:
    - text: 泽
      font_color: [251, 114, 78]
      font_size: 136
    - text: 渡
      font_size: 76
    - text: 可
      font_size: 116
    - text: 可
      font_size: 76
  "平静": [3]
  "喜悦": [3,7]
  "喜爱": [5]
  "惊讶": [8]
  "困惑": [6]
  "无语": [6]
  "悲伤": [2]
  "愤怒": [1]
  "恐惧": [4]
sora:
  full_name: 新海天
  offset: [-200,1820]
  scale: 0.55
  emotion_count: 0
  font: font3
  text:
    - text: 新
      font_color: [137, 177, 251]
      font_size: 136
    - text: 海
      font_size: 116
    - text: 天
      font_size: 76
# 在下方添加新角色信息，依次为全名、表情差分数量、使用字体
# 如：
#   warden:
#     full_name: 典狱长
#     emotion_count: 表情数量
#     offset: 立绘偏移值
#     scale: 立绘缩放
#     font: font3
#     text:
#       - text: 典
#         font_color: [251, 114, 78]
#         font_size: 136
#       - text: 狱
#         font_color: [255, 255, 255] # 字体颜色不填的话默认白色
#         font_size: 76
#       - text: 长
#         font_color: [255, 255, 255]
#         font_size: 116
#       - text: ""
#         font_color: [255, 255, 255]
#         font_size: 76
#     "平静": 
#     "喜悦": 
#     "喜爱": 
#     "惊讶": 
#     "困惑": 
#     "无语": 
#     "悲伤": 
#     "愤怒": 
#     "恐惧": 