nanoka:
  - text: 黑
    font_color: [131, 143, 147]
    font_size: 136
  - text: 部
    font_color: [255, 255, 255]
    font_size: 76
  - text: 奈
    font_color: [255, 255, 255]
    font_size: 116
  - text: 叶香
    font_color: [255, 255, 255]
    font_size: 76

hiro:
  - text: 二
    font_color: [239, 79, 84]
    font_size: 136
  - text: 阶堂
    font_color: [255, 255, 255]
    font_size: 76
  - text: 希
    font_color: [255, 255, 255]
    font_size: 116
  - text: 罗
    font_color: [255, 255, 255]
    font_size: 76

CreatureHiro:
  - text: 二
    font_color: [239, 79, 84]
    font_size: 136
  - text: 阶堂
    font_color: [255, 255, 255]
    font_size: 76
  - text: 希
    font_color: [255, 255, 255]
    font_size: 116
  - text: 罗
    font_color: [255, 255, 255]
    font_size: 76

ema:
  - text: 樱
    font_color: [253, 145, 175]
    font_size: 136
  - text: 羽
    font_color: [255, 255, 255]
    font_size: 76
  - text: 艾
    font_color: [255, 255, 255]
    font_size: 116
  - text: 玛
    font_color: [255, 255, 255]
    font_size: 76

sherry:
  - text: 橘
    font_color: [137, 177, 251]
    font_size: 136
  - text: 雪
    font_color: [255, 255, 255]
    font_size: 116
  - text: 莉
    font_color: [255, 255, 255]
    font_size: 76
  - text: ""

anan:
  - text: 夏
    font_color: [159, 145, 251]
    font_size: 136
  - text: 目
    font_color: [255, 255, 255]
    font_size: 76
  - text: 安
    font_color: [255, 255, 255]
    font_size: 116
  - text: 安
    font_color: [255, 255, 255]
    font_size: 76

noa:
  - text: 城
    font_color: [104, 223, 231]
    font_size: 136
  - text: 崎
    font_color: [255, 255, 255]
    font_size: 76
  - text: 诺
    font_color: [255, 255, 255]
    font_size: 116
  - text: 亚
    font_color: [255, 255, 255]
    font_size: 76

coco:
  - text: 泽
    font_color: [251, 114, 78]
    font_size: 136
  - text: 渡
    font_color: [255, 255, 255]
    font_size: 76
  - text: 可
    font_color: [255, 255, 255]
    font_size: 116
  - text: 可
    font_color: [255, 255, 255]
    font_size: 76

alisa:
  - text: 紫
    font_color: [235, 75, 60]
    font_size: 136
  - text: 藤
    font_color: [255, 255, 255]
    font_size: 76
  - text: 亚
    font_color: [255, 255, 255]
    font_size: 116
  - text: 里沙
    font_color: [255, 255, 255]
    font_size: 76

reia:
  - text: 莲
    font_color: [253, 177, 88]
    font_size: 136
  - text: 见
    font_color: [255, 255, 255]
    font_size: 76
  - text: 蕾
    font_color: [255, 255, 255]
    font_size: 116
  - text: 雅
    font_color: [255, 255, 255]
    font_size: 76

mago:
  - text: 宝
    font_color: [185, 124, 235]
    font_size: 136
  - text: 生
    font_color: [255, 255, 255]
    font_size: 76
  - text: 玛
    font_color: [255, 255, 255]
    font_size: 116
  - text: 格
    font_color: [255, 255, 255]
    font_size: 76

hanna:
  - text: 远
    font_color: [169, 199, 30]
    font_size: 136
  - text: 野
    font_color: [255, 255, 255]
    font_size: 76
  - text: 汉
    font_color: [255, 255, 255]
    font_size: 116
  - text: 娜
    font_color: [255, 255, 255]
    font_size: 76

meruru:
  - text: 冰
    font_color: [227, 185, 175]
    font_size: 136
  - text: 上
    font_color: [255, 255, 255]
    font_size: 76
  - text: 梅
    font_color: [255, 255, 255]
    font_size: 116
  - text: 露露
    font_color: [255, 255, 255]
    font_size: 76

miria:
  - text: 佐
    font_color: [235, 207, 139]
    font_size: 136
  - text: 伯
    font_color: [255, 255, 255]
    font_size: 76
  - text: 米
    font_color: [255, 255, 255]
    font_size: 116
  - text: 莉亚
    font_color: [255, 255, 255]
    font_size: 76

yuki:
  - text: 月
    font_color: [195, 209, 231]
    font_size: 136
  - text: 代
    font_color: [255, 255, 255]
    font_size: 76
  - text: 雪
    font_color: [255, 255, 255]
    font_size: 116
  - text: ""
    font_color: [255, 255, 255]
    font_size: 76
# 在下方添加新角色的文字配置，依次为文字内容、位置（x, y）、字体颜色（R, G, B）、字体大小
# 如：
#  warden:
#    - text: 典
#      position: [ 759, 63 ]
#      font_color: [ 195, 209, 231 ]
#      font_size: 196
#    - text: 狱
#      position: [ 948, 175 ]
#      font_color: [ 255, 255, 255 ]
#      font_size: 92
#    - text: 长
#      position: [ 1053, 117 ]
#      font_color: [ 255, 255, 255 ]
#      font_size: 147
#    - text: ""
#      position: [ 0, 0 ]
#      font_color: [ 255, 255, 255 ]
#      font_size: 135