# config/version.yml
# 版本信息配置

# 当前版本号
version: "1.5.7"

# 版本历史 记录的是exe的更新，并非代码的更新记录
history:
  - version: "1.5.7"
    date: "2025-12-16"
    description:
      - "添加了关于窗口，并提供了检查更新功能"
      - "添加了表情筛选功能"
      - "修复了一些已知bug（"
  - version: "1.5.5"
    date: "2025-12-14"
    description:
      - "添加了魔女化希罗的表情并补齐了原本缺失的表情（指哭哭表情）"
      - "重做了图片合成时的逻辑以及最终效果"
      - "角色图片及背景资源全换为了webp格式， 程序体积减小了（"
      - "默认隐藏情感匹配入口，因为不会用的人比较多(请手动在settings.yml的sentiment_matching段落中启用display)"
      - "快捷键编辑改为使用监听的方式， 可以在settings.yml中修改快捷键"
      - "角色和背景图片支持更多格式， 包括png、jpg、jpeg、webp等"
  - version: "1.5.2"
    date: "2025-12-04"
    description:
      - "合并和精简了代码和使用的模块，程序体积减小了（"
      - "修复了快捷键响应不灵敏的bug"
      - "修复了无法正常使用额外添加到ai模型的bug"
  - version: "1.5.1"
    date: "2025-12-03"
    description: 
      - "使用本地emoji图片（素材来自noto emoji）绘制emoji，大幅提升了绘制emoji时的速度"
      - "大幅扩展了可正常绘制的emoji范围（但是部分复杂组合emoji仍会绘制出错， 比如各种奇怪肤色的人亲亲以及家庭组合的emoji）"
      - "把括号移除出了强调字符的范围"
  - version: "1.4.6"
    date: "2025-12-01"
    description: "初始版本"

# 程序信息
program:
  name: "魔裁文本框生成器"
  author:
    - "oplivilqo"
    - "Kwicxy"
    - "YangQwQ"
    - "morpheus315"
    - "BaiJin0224"
    - "CCYellowStar2"
  description: "魔裁文本框生成工具"
  github: "https://github.com/YangQwQ/ManosabaTextbox-GUI"
  origin_project: "https://github.com/oplivilqo/manosaba_text_box"
  
# 联系信息
contact:
  qq_group:
    - "1037032551"